apiVersion: v1
kind: Service
metadata:
  name: dog-cat-classifier-service
spec:
  selector:
    app: dog-cat-classifier
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: LoadBalancer
